# =========================================================
# APPLICATION
# =========================================================

spring.application.name=url-shortener

server.port=8080


# =========================================================
# MYSQL DATABASE
# =========================================================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/url_shortener?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=Yogeshbhatt@2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false


# =========================================================
# FLYWAY
# =========================================================

spring.flyway.enabled=true

spring.flyway.locations=classpath:db/migration


# =========================================================
# REDIS
# =========================================================

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Distributed Lock
app.distributed-lock.expiration-seconds=10


# =========================================================
# CACHE
# =========================================================

spring.cache.type=redis

spring.cache.redis.time-to-live=3600000

spring.cache.redis.cache-null-values=false


# =========================================================
# ACTUATOR
# =========================================================

management.endpoints.web.exposure.include=health,info,metrics

management.endpoint.health.show-details=when-authorized


# =========================================================
# THREAD POOL
# =========================================================

app.thread-pool.core-size=10
app.thread-pool.max-size=50
app.thread-pool.queue-capacity=100


# =========================================================
# RATE LIMITING
# =========================================================

app.rate-limit.capacity=100
app.rate-limit.refill-tokens=100
app.rate-limit.refill-duration-seconds=60


# =========================================================
# URL EXPIRATION
# =========================================================

app.url-expiration-hours=4